# nominal config: right hip, right knee, left hip, left knee
# [-0.45, 1.15, -0.45, 1.15])

################################# STAND ########################################

stand:
  # Path to URDF
  model_file: "../models/urdf/harpy_planar_CIMPC.urdf"

  # MPC parameters
  T: 8.0  # total time horizon
  dt: 0.1 # time step

  # Cost Parameters
  Qq:   [60, 50, 1, 0.1, 0.1, 0.1, 0.1]
  Qv:   [100, 5, 1, 10, 10, 10, 10]
  R:    [1_000_000, 1_000_000, 1_000_000, 0.01, 0.01, 0.01, 0.01]
  Qf_q: [60, 60, 1, 1, 1, 1, 1]
  Qf_v: [20, 20, 0.2, 0.2, 0.2, 0.2, 0.2]

  # X, Z, THETA, R_HIP, R_KNEE, L_HIP, L_KNEE 
  ctrl_pts: 
  - [ 0.,    0.,    0.0,   0.0,   0.0 ]
  - [ 0.52,  0.52,  0.52,  0.52,  0.52]
  - [ 0.,    0.,    0.,    0.,    0.  ]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]

################################# WALK ########################################

walk:
  # Path to URDF
  model_file: "../models/urdf/harpy_planar_CIMPC.urdf"

  # MPC parameters
  T: 10.0  # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  Qq:   [60, 50, 1, 5, 5, 5, 5]
  Qv:   [100, 5, 1, 10, 10, 10, 10]
  R:    [100_000, 100_000, 100_000, 0.01, 0.01, 0.01, 0.01]
  Qf_q: [60, 60, 1, 1, 1, 1, 1]
  Qf_v: [20, 20, 0.2, 0.2, 0.2, 0.2, 0.2]

  # X, Z, THETA, R_HIP, R_KNEE, L_HIP, L_KNEE 
  ctrl_pts: 
  - [ 0.,    0.75,    1.5,   2.25,   3.0 ]
  - [ 0.52,  0.52,  0.52,  0.52,  0.52]
  - [ 0.,    0.,    0.,    0.,    0.  ]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]


################################# JUMP ########################################

jump:
  # Path to URDF
  model_file: "../models/urdf/harpy_planar_CIMPC.urdf"

  # MPC parameters
  T: 4.0  # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  Qq:   [200, 30, 1, 70, 70, 70, 70]
  Qv:   [20, 30,  1, 30, 30, 30, 30]
  R:    [100_000, 100_000, 100_000, 1, 1, 1, 1]
  Qf_q: [900, 200, 10, 100, 100, 100, 100]
  Qf_v: [200, 200, 10, 100, 100, 100, 100]

  # X, Z, THETA, R_HIP, R_KNEE, L_HIP, L_KNEE 
  ctrl_pts: 
  - [ 0.,    0.,    0.5,   1.,  1.]
  - [ 0.52,  0.5,  0.71,  0.5,  0.52]
  - [ 0.,    0.,    0.,    -0.,    -0.]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]

################################# FLIP ########################################

front_flip:
  # Path to URDF
  model_file: "../models/urdf/harpy_planar_CIMPC_staicase.urdf"

  # MPC parameters
  T: 4.0  # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  Qq:   [200, 30, 1, 70, 70, 70, 70]
  Qv:   [20, 30,  1, 30, 30, 30, 30]
  R:    [100_000, 100_000, 100_000, 1, 1, 1, 1]
  Qf_q: [900, 200, 10, 100, 100, 100, 100]
  Qf_v: [200, 200, 10, 100, 100, 100, 100]

  # X, Z, THETA, R_HIP, R_KNEE, L_HIP, L_KNEE 
  ctrl_pts: 
  - [ 0.,    0.,    0.5,   1.,  1.]
  - [ 0.52,  0.5,  0.71,  0.5,  0.52]
  - [ 0.,    0.,    0.,    -0.,    -0.]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]
  - [-0.45, -0.45, -0.45, -0.45, -0.45]
  - [ 1.15,  1.15,  1.15,  1.15,  1.15]
